### ISSUE TITLE
Attachments used in Admonition code blocks are not recognized

### ISSUE THREAD

**Issue by chenxuan353** [Vinzent03/find-unlinked-files#28]
as the title suggests

-------

I see that this issue is also included in the [File Cleaner](https://github.com/Johnson0907/obsidian-file-cleaner) plugin, perhaps it should be warned about in the documentation, or an attempt made to fix it.

**Comment by Vinzent03** [comment]
That's because Obsidian doesn't recognize it as a link. So there's nothing I can do. I strongly suggest you to use [Callouts](https://help.obsidian.md/How+to/Use+callouts) from Obsidian itself. Admonition works with callouts too and enhances them. See their [README](https://github.com/valentine195/obsidian-admonition#please-note).
