### ISSUE TITLE
[FR] Find unlinked images/attachments

### ISSUE THREAD

**Issue by user30535** [Vinzent03/find-unlinked-files#32]
Hi,

Is it possible to add `find unlinked images/attachments` feature? This allows users to decide whether to delete or link the unlinked attachments.

Thank you!

**Comment by Vinzent03** [comment]
You can already do that by specifying the file types in the settings.

**Comment by EnidanBri** [comment]
Hi! 
I have the same question, and I don't get it. I looked through all the settings and I can't find anything with would make the plugin search unlinked media. 
Nearly all the options are about **excluding** files or folders. So that, means, if I don't specify anything there, I don't exclude anything, right? 
I only activated the first option in the settings to open the results file, everything else is blank or not active. 
Shouldn't the plugin then search through everything, including the attachments?

For me, the plugin doesn't find anything...
The results files are always empty.
