### ISSUE TITLE
Is there any way to recognize when a file is only linked by a dataview query?

### ISSUE THREAD

**Issue by haemi** [Vinzent03/find-unlinked-files#44]
I know it's a lot to ask for, but I'm looking for a way to find files that are currently not linked at all, not even by a dataview query

**Comment by Vinzent03** [comment]
I'm not really familiar with the dataview plugin, but I think your issue title and description don't match?

**Comment by claudius-krause** [comment]
I'm having the same question. I use the dataview plugin to create tables of content files. For example, dataview creates a table containing all notes that have a given tag. 
The links in these tables are not seen by this plugin, as all the files still appear in the created .md file, even though they are linked through the dataview table.

**Comment by Vinzent03** [comment]
I'm working with the metadata cache from Obsidian. Basically the same data that is used to build the graph view. Again, I don't know exactly how dataview works, but I don't think that's cached there and instead calculated dynamically when the page is opened. I won't add support for dataview queries, because of performance reasons, and I'm not familiar with how I would access these links.
