### ISSUE TITLE
False positive on orphaned files

### ISSUE THREAD

**Issue by Smitty010** [Vinzent03/find-unlinked-files#45]
Here's an excerpt from a file:
```
9. Go to the **Hide My Email** menu and open your recently created email address.
    
        ![[how-to-create-a-fake-email-address-and-why-you-should-generate-fake-alias-email-addresses-15.jpg]]
   
```

the plugin reports the above as an orphaned file.  I can also look for the file and it shows up in both the .md file and the "unlinked files.output.md" file.  If I change it to (removing the leading spaces):

```
9. Go to the **Hide My Email** menu and open your recently created email address.
    
![[how-to-create-a-fake-email-address-and-why-you-should-generate-fake-alias-email-addresses-15.jpg]]
```
Then the problem goes away (i.e., the file is no longer reported as orphaned.

**Comment by Vinzent03** [comment]
I'm working with the cache provided by Obsidian, which in this case corresponds to the backlinks pane. Obsidian doesn't track your link as backlink, because you created a code block with your indent, which you should see in reading view. Obsidian doesn't track links in code blocks. So there is nothing I can do from my side. Please don't indent the line if you wish the link to work.
